name: Build tool

on:
  push:
    # ???
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        release-type: [win-x86, win-x64, win-arm]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build UndertaleModTool --no-restore
    - name: Publish
      run: dotnet publish UndertaleModTool -c Release -r ${{ matrix.release-type }} --self-contained false -p:PublishSingleFile=true --output output
    - name: Copy documents
      run: |
        Copy-Item "README.md" -Destination "./output/"
        Copy-Item "SCRIPTS.md" -Destination "./output/"
    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.release-type }}
        path: output
